apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloword-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloword-api-v1
  template:
    metadata:
      labels:
        app: helloword-api-v1
    spec:
      containers:
        - name: helloword-api-v1
          image: nishantdoshi9/nishrepo:helloapi
          ports:
            - containerPort: 8085
          env:
            - name: PORT
              value: "8085"
---
apiVersion: v1
kind: Service
metadata:
  name: helloword-api-v1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8085
  selector:
    app: helloword-api-v1